blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/expressive-code/expressive-code/discussions/new?category=feature-requests
    about: Suggest an improvement youâ€™d like to see added to Expressive Code
  - name: â“ Support Question
    url: https://github.com/expressive-code/expressive-code/discussions/new?category=q-a
    about: 'This issue tracker is not for support questions. Ask in GitHub Discussions for assistance!'
